SELECT * FROM TB_POPLTN_DATA;
SELECT * FROM TB_POPLTN;

WITH TEMP_POPLTN_SE_CNT AS(
    SELECT 
        ADMINIST_ZONE_NO, 
        ADMINIST_ZONE_NM, 
        POPLTN_SE_CD,
        SUM(POPLTN_CNT) AS EMD_SE_POPLTN_CNT
    FROM TB_POPLTN
    WHERE ADMINIST_ZONE_NO NOT LIKE "_____00000"
        AND STD_MT = "202304"
        AND POPLTN_SE_CD IN ("M", "F")
    GROUP BY POPLTN_SE_CD, ADMINIST_ZONE_NO, ADMINIST_ZONE_NM
)